import { systemToolsGroup } from '../../data/systemTools';
import type {
  AppConfig,
  AutoSaveSettings,
  BehaviorSettings,
  DisplaySettings,
  Group,
  NoteSettings,
  RainbowSettings,
  WindowControlId,
  WindowState,
} from '../../types';
import {
  DEFAULT_GLOBAL_SEARCH_SETTINGS,
  DEFAULT_IMAGE_BROWSER_SETTINGS,
  DEFAULT_TRANSFER_STATION_SETTINGS,
} from '../../utils/v16Types';
import { defaultExperience } from '../../lib/experienceSettings';
import { defaultShortcutSettings } from '../../lib/keyboardShortcuts';
import { defaultBrowserRouter } from '../../lib/browserRouter';

export const DEFAULT_WINDOW_CONTROL_ORDER: WindowControlId[] = [
  'search',
  'transfer',
  'image',
  'profiles',
  'sortGroups',
  'add',
  'settingsQuick',
  'settings',
  'pin',
  'minimize',
  'close',
];

export const defaultDisplay: DisplaySettings = {
  fontFamily: '',
  fontApplyAreas: [],
  labelLines: 2,
  charsPerLine: 8,
  fontSize: 12,
  iconSize: 52,
  itemIconResolveMode: 'auto',
  iconParallelTasks: 6,
  autoSaveWebsiteIcon: true,
  faviconProvider: 'auto',
  faviconProviderFallback: true,
  toastDurationMs: 2400,
  itemWidth: 108,
  itemHeight: 116,
  gridGap: 14,
  viewMode: 'grid',
  sortMode: 'custom',
  menuFontSize: 14,
  menuItemHeight: 34,
  menuMinWidth: 210,
  topTabEqualWidth: false,
  topTabWidth: 104,
  topTabHeight: 32,
  topTabGap: 8,
  topTabFontSize: 14,
  topTabBorderWidth: 1,
  topTabColorStrength: 0.17,
  topTabShape: 'round',
  sidebarWidth: 176,
  sidebarItemHeight: 38,
  sidebarItemGap: 8,
  sidebarFontSize: 14,
  sidebarItemRadius: 12,
  uiScale: 1,
  mainUiScale: 1,
  settingsUiScale: 1,
  scrollbarSize: 12,
  scrollbarRadius: 999,
  scrollbarUseThemeColor: true,
  scrollbarThumbColor: '#8A8F98',
  scrollbarThumbHoverColor: '#5B8DEF',
  scrollbarTrackColor: 'rgba(0, 0, 0, 0.08)',
  rememberInterfaceCollapseState: false,
  interfaceCollapsedSections: [],
  windowControlStyle: 'pad',
  windowControlSize: 34,
  windowControlGap: 8,
  windowControlOrder: DEFAULT_WINDOW_CONTROL_ORDER,
  windowControlHidden: [],
  backgroundEnabled: false,
  backgroundImage: '',
  backgroundMediaKind: 'auto',
  backgroundOpacity: 0.62,
  backgroundDim: 0.18,
  backgroundBlur: 0,
  backgroundFit: 'cover',
  backgroundPosition: 'center',
  backgroundPositionX: 50,
  backgroundPositionY: 50,
  backgroundMotionEnabled: true,
  backgroundPlaybackRate: 1,
  backgroundPauseWhenHidden: true,
  backgroundContainAmbient: true,
  backgroundPanelOpacity: 0.86,
  settingsBackgroundEnabled: false,
  settingsBackgroundImage: '',
  settingsBackgroundMediaKind: 'auto',
  settingsBackgroundOpacity: 0.62,
  settingsBackgroundDim: 0.18,
  settingsBackgroundBlur: 0,
  settingsBackgroundFit: 'cover',
  settingsBackgroundPosition: 'center',
  settingsBackgroundPositionX: 50,
  settingsBackgroundPositionY: 50,
  settingsBackgroundMotionEnabled: true,
  settingsBackgroundPlaybackRate: 1,
  settingsBackgroundPauseWhenHidden: true,
  settingsBackgroundContainAmbient: true,
  settingsBackgroundPanelOpacity: 0.9,
  settingsBackgroundGlassEffect: false,
  settingsBackgroundGlassBlur: 22,
  settingsBackgroundGlassSaturation: 1.32,
  settingsBackgroundGlassHighlight: 0.72,
};

export const defaultBehavior: BehaviorSettings = {
  edgeAutoHide: true,
  edgeHideDelaySeconds: 0,
  edgeAnimationMs: 90,
  edgeAnimationStyle: 'animate-window',
  autoEdgeHide: true,
  autoEdgeBounce: true,
  autoEdgeSnapBack: false,
  autoEdgeSnapBackAnimation: true,
  autoEdgeSnapBackAnimationMs: 220,
  autoEdgeHideDelay: 1000,
  edgeVisiblePixels: 5,
  edgeGhostFrameFix: true,
  edgeMouseLeaveHideMs: 90,
  edgeUseMainWindowStrip: true,
  edgeStripSize: 10,
  edgeStripOpacity: 0.88,
  edgeStripUseThemeColor: true,
  edgeStripColor: '#C36A2D',
  launchMode: 'double',
  urlOpenMode: 'default',
  autoStart: false,
  closeAction: 'tray',
  alwaysOnTop: false,
  rememberMainWindowBounds: true,
  manualWindowStateEnabled: false,
  restoreWindowStateOnLaunch: true,
  saveWindowStateOnExit: true,
  rememberSettingsPanelBounds: true,
  settingsPanelAdaptiveSize: true,
  itemDragLongPressMs: 220,
  itemDragTolerance: 10,
  itemDragBackgroundColor: '#5b8def',
  itemDragGlowColor: '#5b8def',
  itemDragGlowBrightness: 0.72,
  promptRenameDroppedWebsite: true,
};

export const defaultWindowState: WindowState = {
  opacity: 0.96,
  edgeAutoHide: true,
};

export const defaultAutoSave: AutoSaveSettings = {
  enabled: false,
  directory: '',
  intervalMinutes: 10,
  fileName: 'win-launcher-config-autosave.json',
};

export const defaultNotes: NoteSettings = {
  fontSize: 15,
  lineHeight: 1.7,
  padding: 16,
  radius: 16,
  autosaveDelayMs: 450,
  wrap: true,
  showTitle: true,
  showLineNumbers: false,
  lineNumberScope: 'all',
  separatorLength: 14,
  dashSeparatorChar: '—',
  starSeparatorChar: '*',
};

export const defaultRainbow: RainbowSettings = {
  enabled: false,
  cursorEnabled: true,
  cursorStyle: 'dot-ring',
  cursorSize: 18,
  trailEnabled: true,
  trailCount: 18,
  trailDurationMs: 700,
  trailSize: 8,
  trailBrightness: 0.8,
  borderEnabled: true,
  borderMode: 'fixed-flow',
  borderSpeedSeconds: 18,
  borderWidth: 2,
  borderBrightness: 0.75,
  textEnabled: true,
  textOnGroups: true,
  textOnDirectories: false,
  textOnSettings: false,
  textSpeedSeconds: 26,
  cursorColors: ['#ff3b30', '#ff9500', '#ffcc00', '#34c759', '#00c7be', '#007aff', '#af52de'],
  borderColors: ['#ff6bcb', '#7c5cff', '#34d3ff', '#35ff89', '#ffe66d'],
  textColors: ['#ff5f6d', '#ffc371', '#42e695', '#3bb2b8', '#8e54e9'],
};

const userGroup: Group = {
  id: 'group_default',
  name: '我的快捷方式',
  order: 1,
  directories: [
    {
      id: 'dir_default',
      name: '常用',
      order: 0,
      kind: 'normal',
      items: [],
    },
  ],
};

export function cloneConfig(): AppConfig {
  return {
    groups: [systemToolsGroup, userGroup],
    theme: 'dark-soft',
    display: { ...defaultDisplay },
    behavior: { ...defaultBehavior },
    browserRouter: { ...defaultBrowserRouter, customBrowsers: [], profileOverrides: {} },
    windowState: { ...defaultWindowState },
    autoSave: { ...defaultAutoSave },
    transferItems: [],
    imageBrowserItems: [],
    globalSearch: { ...DEFAULT_GLOBAL_SEARCH_SETTINGS },
    transferStation: { ...DEFAULT_TRANSFER_STATION_SETTINGS },
    imageBrowser: { ...DEFAULT_IMAGE_BROWSER_SETTINGS },
    notes: { ...defaultNotes },
    rainbow: { ...defaultRainbow },
    experience: { ...defaultExperience },
    shortcuts: { ...defaultShortcutSettings },
    commandUsage: {},
  };
}
